auth:
  jwt:
    enabled: true
    secret: "Gm/dZyJQfEJxC0tDdHlQYxZxVa4vX2RkYXJrbmV0VmFsaWRLZXlNYWtlU3VyZQ=="
    access-token-expiration: 86400000  # 24 hours
    refresh-token-expiration: 604800000  # 7 days

  session:
    enabled: true
    store-type: jdbc  # Store session in the database

  refresh-token:
    enabled: true

  logging:
    enabled: true

  cookies:
    enabled: true
    name: "AuthRefreshToken"
    http-only: true     # Prevent JavaScript access (recommended for security)
    secure: false       # Set to true in production with HTTPS
    same-site: "Strict" # Prevent CSRF attacks
    max-age: 604800     # 7 days in seconds

