auth:
  enable-jwt: true
  enable-session: true
  enable-oauth2: false
  enable-rbac: true
  enable-refresh-token: true
  enable-logging: true
  enable-cookies: true  # Enable cookies for storing refresh tokens
  cookie-name: "AuthRefreshToken"  # Cookie name
  cookie-http-only: true  # Prevent JavaScript access (recommended for security)
  cookie-secure: false  # Set to true in production with HTTPS
  cookie-same-site: "Strict"  # Prevent CSRF attacks
  cookie-max-age: 604800  # 7 days in seconds

jwt:
  secret: "Gm/dZyJQfEJxC0tDdHlQYxZxVa4vX2RkYXJrbmV0VmFsaWRLZXlNYWtlU3VyZQ=="
  access-token-expiration: 86400000  # 24 hours
  refresh-token-expiration: 604800000  # 7 days

spring:
  session:
    store-type: jdbc  # Store session in the database
