name: Publish to Maven Central (manual)

on:
  workflow_dispatch: {}

concurrency:
  group: central-publish-${{ github.ref }}
  cancel-in-progress: false

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Temurin JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Import GPG private key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          git_user_signingkey: false
          git_commit_gpgsign: false

      - name: Configure Maven settings.xml for Central
        run: |
          mkdir -p ~/.m2
          cat > ~/.m2/settings.xml << 'XML'
          <settings>
            <servers>
              <server>
                <id>central</id>
                <username>${{ secrets.CENTRAL_USERNAME }}</username>
                <password>${{ secrets.CENTRAL_PASSWORD }}</password>
              </server>
            </servers>
            <profiles>
              <profile>
                <id>gpg</id>
                <properties>
                  <gpg.executable>gpg</gpg.executable>
                  <gpg.keyname>1460C856C8059B29</gpg.keyname>
                </properties>
              </profile>
            </profiles>
            <activeProfiles>
              <activeProfile>gpg</activeProfile>
            </activeProfiles>
          </settings>
          XML

      - name: Fail if version is SNAPSHOT
        run: |
          VERSION=$(mvn -q -DforceStdout help:evaluate -Dexpression=project.version)
          echo "Project version: $VERSION"
          if echo "$VERSION" | grep -qi -- "-SNAPSHOT$"; then
            echo "::error :: SNAPSHOT versions cannot be published to Central."
            exit 1
          fi

      - name: Fail if version already exists on Central (enforce bump)
        run: |
          VERSION=$(mvn -q -DforceStdout help:evaluate -Dexpression=project.version)
          GROUP_ID=$(mvn -q -DforceStdout help:evaluate -Dexpression=project.groupId)
          ARTIFACT_ID=$(mvn -q -DforceStdout help:evaluate -Dexpression=project.artifactId)
          GROUP_PATH=${GROUP_ID//.//}
          URL="https://repo1.maven.org/maven2/${GROUP_PATH}/${ARTIFACT_ID}/${VERSION}/${ARTIFACT_ID}-${VERSION}.pom"
          echo "Checking Central URL: $URL"
          STATUS=$(curl -s -o /dev/null -w "%{http_code}" "$URL")
          if [ "$STATUS" = "200" ]; then
            echo "::error :: Version $VERSION already exists on Maven Central. Bump <version> in pom.xml."
            exit 1
          fi

      - name: Build, sign, and publish (skip tests)
        run: |
          export GPG_TTY=$(tty)
          mvn -B -U -Dmaven.test.skip=true -DskipTests=true clean deploy
